### PR TITLE
Fix broken dependency

### PR DESCRIPTION
**Pull request by jdtzmn**
The previous link broke, and this link works!

### CODE REVIEW

**Comment by nutgaard** [comment]
Out of curiosity, is this library  something you use?

**Comment by nutgaard** [comment]
Thanks for the PR. ☺

**Comment by jdtzmn** [comment]
Yes! Currently working on a web app that will sync you with other spotify users, and this repository is VERY helpful.

**Comment by nutgaard** [comment]
Aha.. Cool. :) Let me know if there is anything you need, and I may be able to help. 
As of now I've created a new release (v.0.0.8), published it to npm and added a license (Unlicense, so super-permissive), just in case you were using a dependency from there.

**Pull request merged**
